server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?userSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typs-aliases-package: com.jdai.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.jdai: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

